2019-12-12 19:46:44 WARN  UserDAOIMPL:112 - Unable to retrieve all users
org.postgresql.util.PSQLException: No value specified for parameter 7.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:108)
	at com.revature.services.UserService.addUser(UserService.java:22)
	at com.revature.Driver.main(Driver.java:19)
2019-12-12 19:51:15 WARN  UserDAOIMPL:112 - Unable to add user
org.postgresql.util.PSQLException: No value specified for parameter 7.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:108)
	at com.revature.services.UserService.addUser(UserService.java:22)
	at com.revature.Driver.main(Driver.java:19)
2019-12-12 19:52:16 WARN  UserDAOIMPL:112 - Unable to add user
org.postgresql.util.PSQLException: ERROR: column "is_looged_in" of relation "users" does not exist
  Position: 79
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:108)
	at com.revature.services.UserService.addUser(UserService.java:22)
	at com.revature.Driver.main(Driver.java:19)
2019-12-12 20:05:37 WARN  UserDAOIMPL:112 - Unable to add user
org.postgresql.util.PSQLException: ERROR: insert or update on table "users" violates foreign key constraint "users_account_id_fkey"
  Detail: Key (account_id)=(2) is not present in table "accounts".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:108)
	at com.revature.services.UserService.addUser(UserService.java:22)
	at com.revature.Driver.main(Driver.java:19)
2019-12-13 07:40:29 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: INSERT has more expressions than target columns
  Position: 114
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:156)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 07:45:53 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: column "pin_number" is of type integer but expression is of type boolean
  Hint: You will need to rewrite or cast the expression.
  Position: 123
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:156)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 07:47:41 WARN  UserDAOIMPL:209 - Unable to retrieve the account
org.postgresql.util.PSQLException: The column name account_type was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repository.AccountDAOIMPL.getAccountIdBYPinNumber(AccountDAOIMPL.java:196)
	at com.revature.services.AccountServices.getAccountBYPinNumber(AccountServices.java:41)
	at com.revature.Driver.createUser(Driver.java:157)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:49:16 WARN  UserDAOIMPL:297 - Unable to retrieve the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:75)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:49:16 WARN  UserDAOIMPL:297 - Unable to retrieve the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:82)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:50:14 WARN  UserDAOIMPL:297 - Unable to retrieve the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:75)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:50:14 WARN  UserDAOIMPL:297 - Unable to retrieve the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:82)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:51:44 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:75)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:51:44 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:82)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:52:54 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 51
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:75)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:52:54 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 51
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:82)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 10:57:45 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 34
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFname(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFname(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:76)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 11:03:44 WARN  UserDAOIMPL:297 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: column "shiva" does not exist
  Position: 34
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repository.UserDAOIMPL.getUserByFname(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFname(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:76)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 11:16:15 WARN  UserDAOIMPL:300 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:75)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 11:16:15 WARN  UserDAOIMPL:300 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repository.UserDAOIMPL.getUserByFnameAndPassword(UserDAOIMPL.java:280)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:48)
	at com.revature.Driver.checkUserInDB(Driver.java:83)
	at com.revature.Driver.checkUser(Driver.java:45)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 11:59:12 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: relation "account_number_squence" does not exist
  Where: PL/pgSQL function set_account_number() line 3 at assignment
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:152)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 11:59:12 WARN  UserDAOIMPL:125 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (user_id)=(5) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:121)
	at com.revature.services.UserService.addUser(UserService.java:24)
	at com.revature.Driver.checkUser(Driver.java:42)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 12:02:09 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: relation "account_number_squence" does not exist
  Where: PL/pgSQL function set_account_number() line 3 at assignment
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:152)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 12:03:26 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: relation "account_number_sequence" does not exist
  Where: PL/pgSQL function set_account_number() line 3 at assignment
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:152)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 12:55:49 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: relation "account_number_sequence" does not exist
  Where: PL/pgSQL function set_account_number() line 3 at assignment
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:152)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 12:57:33 WARN  UserDAOIMPL:116 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: control reached end of trigger procedure without RETURN
  Where: PL/pgSQL function set_account_number()
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:112)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:29)
	at com.revature.Driver.createUser(Driver.java:152)
	at com.revature.Driver.checkUser(Driver.java:41)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-13 21:10:22 WARN  UserDAOIMPL:259 - Unable to update the account balance
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 31
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.updateBalanceOfAccount(AccountDAOIMPL.java:255)
	at com.revature.services.AccountServices.updateBalanceOfAccount(AccountServices.java:45)
	at com.revature.Driver.deposit(Driver.java:160)
	at com.revature.Driver.logIn(Driver.java:130)
	at com.revature.Driver.checkUser(Driver.java:58)
	at com.revature.Driver.start(Driver.java:27)
	at com.revature.App.main(App.java:9)
2019-12-14 21:46:08 WARN  UserDAOIMPL:126 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(RamKB) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:122)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:316)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 21:56:23 WARN  UserDAOIMPL:126 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(RamKB) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:122)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:01:05 WARN  UserDAOIMPL:126 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(zzz) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:122)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:03:22 WARN  UserDAOIMPL:173 - Unable to update the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.updateUser(UserDAOIMPL.java:169)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:04:21 WARN  UserDAOIMPL:173 - Unable to update the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.updateUser(UserDAOIMPL.java:169)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:11:07 WARN  UserDAOIMPL:173 - Unable to update the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.updateUser(UserDAOIMPL.java:169)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:13:17 WARN  UserDAOIMPL:173 - Unable to update the user
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.updateUser(UserDAOIMPL.java:169)
	at com.revature.services.UserService.updateUser(UserService.java:28)
	at com.revature.Driver.giveOptionsToModifyUsers(Driver.java:292)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:152)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:23:43 WARN  UserDAOIMPL:160 - Unable to update the user's account
org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
  Position: 31
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.updateAccount(AccountDAOIMPL.java:156)
	at com.revature.services.AccountServices.updateAccount(AccountServices.java:33)
	at com.revature.Driver.giveOptionsToModifyAccounts(Driver.java:221)
	at com.revature.Driver.seeDetailsAboutUsers(Driver.java:153)
	at com.revature.Driver.logIn(Driver.java:122)
	at com.revature.Driver.checkUser(Driver.java:43)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-14 22:48:51 WARN  UserDAOIMPL:126 - Unable to add user
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(50)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:122)
	at com.revature.services.UserService.addUser(UserService.java:24)
	at com.revature.Driver.checkUser(Driver.java:37)
	at com.revature.Driver.start(Driver.java:22)
	at com.revature.App.main(App.java:9)
2019-12-16 18:16:08 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.utils.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repository.UserDAOIMPL.getAllUsers(UserDAOIMPL.java:28)
	at com.revature.repository.UserDAOIMPL.getAllUsersPassword(UserDAOIMPL.java:60)
	at com.revature.services.UserService.getAllUsersPassword(UserService.java:44)
	at com.revature.Driver.conformPassword(Driver.java:177)
	at com.revature.Driver.createUser(Driver.java:205)
	at com.revature.Driver.checkUser(Driver.java:37)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at org.postgresql.core.PGStream.<init>(PGStream.java:75)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 15 more
2019-12-16 18:18:17 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.utils.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repository.UserDAOIMPL.getAllUsers(UserDAOIMPL.java:28)
	at com.revature.repository.UserDAOIMPL.getAllUsersPassword(UserDAOIMPL.java:60)
	at com.revature.services.UserService.getAllUsersPassword(UserService.java:44)
	at com.revature.Driver.conformPassword(Driver.java:177)
	at com.revature.Driver.createUser(Driver.java:205)
	at com.revature.Driver.checkUser(Driver.java:37)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at org.postgresql.core.PGStream.<init>(PGStream.java:75)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 15 more
2019-12-16 18:23:07 WARN  UserDAOIMPL:118 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(ppp) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:114)
	at com.revature.services.UserService.addUser(UserService.java:24)
	at com.revature.Driver.checkUser(Driver.java:39)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 18:25:28 WARN  UserDAOIMPL:118 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(zzz) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:114)
	at com.revature.services.UserService.addUser(UserService.java:24)
	at com.revature.Driver.checkUser(Driver.java:39)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 18:35:59 WARN  UserDAOIMPL:118 - Unable to add user
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_password_key"
  Detail: Key (password)=(www) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.UserDAOIMPL.addUser(UserDAOIMPL.java:114)
	at com.revature.services.UserService.addUser(UserService.java:24)
	at com.revature.Driver.checkUser(Driver.java:39)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 18:48:42 WARN  UserDAOIMPL:123 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_user_id_fkey"
  Detail: Key (user_id)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:119)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:30)
	at com.revature.Driver.checkUser(Driver.java:52)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 18:53:32 WARN  UserDAOIMPL:123 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_user_id_fkey"
  Detail: Key (user_id)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:119)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:30)
	at com.revature.Driver.checkUser(Driver.java:52)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 20:38:21 WARN  UserDAOIMPL:91 - Unable to retrieve all accounts
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.repository.AccountDAOIMPL.getAllAccountsOfUser(AccountDAOIMPL.java:72)
	at com.revature.services.AccountServices.getAllAccountsOfUser(AccountServices.java:22)
	at com.revature.Driver.displayAccounts(Driver.java:530)
	at com.revature.Driver.showUsersAccountInfo(Driver.java:264)
	at com.revature.Driver.logIn(Driver.java:133)
	at com.revature.Driver.checkUser(Driver.java:68)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-16 20:45:16 WARN  UserDAOIMPL:91 - Unable to retrieve all accounts
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.repository.AccountDAOIMPL.getAllAccountsOfUser(AccountDAOIMPL.java:72)
	at com.revature.services.AccountServices.getAllAccountsOfUser(AccountServices.java:22)
	at com.revature.Driver.displayAccounts(Driver.java:530)
	at com.revature.Driver.showUsersAccountInfo(Driver.java:264)
	at com.revature.Driver.logIn(Driver.java:133)
	at com.revature.Driver.checkUser(Driver.java:68)
	at com.revature.Driver.start(Driver.java:23)
	at com.revature.App.main(App.java:9)
2019-12-17 13:19:25 INFO  App:11 - Begin the Application
2019-12-17 13:21:50 INFO  App:11 - Begin the Application
2019-12-17 13:24:12 INFO  App:11 - Begin the Application
2019-12-17 13:27:17 INFO  App:11 - Begin the Application
2019-12-17 13:28:45 INFO  App:11 - Begin the Application
2019-12-17 13:32:27 INFO  App:11 - Begin the Application
2019-12-17 13:32:47 INFO  Driver:58 - User hhh hhhsaved in database
2019-12-17 13:33:00 INFO  Driver:76 - Account with account number = 0 was saved
2019-12-17 17:15:05 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.utils.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:134)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:30)
	at com.revature.services.AccountServices.createAccountWithUser(AccountServices.java:59)
	at com.revature.AccountServicesTest.test(AccountServicesTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at org.postgresql.core.PGStream.<init>(PGStream.java:75)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 35 more
2019-12-17 17:16:09 WARN  AccountDAOIMPL:155 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_user_id_fkey"
  Detail: Key (user_id)=(2) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:151)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:30)
	at com.revature.services.AccountServices.createAccountWithUser(AccountServices.java:59)
	at com.revature.AccountServicesTest.test(AccountServicesTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-17 17:24:14 WARN  AccountDAOIMPL:155 - Unable to add  account
org.postgresql.util.PSQLException: ERROR: insert or update on table "accounts" violates foreign key constraint "accounts_user_id_fkey"
  Detail: Key (user_id)=(2) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repository.AccountDAOIMPL.addAccount(AccountDAOIMPL.java:151)
	at com.revature.services.AccountServices.addAccount(AccountServices.java:30)
	at com.revature.services.AccountServices.createAccountWithUser(AccountServices.java:59)
	at com.revature.AccountServicesTest.testCreateAccountWithUserWithCorrectInformation(AccountServicesTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
2019-12-18 10:36:31 INFO  App:11 - Begin the Application
2019-12-18 10:37:30 INFO  Driver:58 - User sundar kashisaved in database
2019-12-18 10:38:00 INFO  Driver:76 - Account with account number = 0 was saved
2019-12-18 10:42:30 INFO  App:11 - Begin the Application
